"""Add models

Revision ID: 31a999f49cdc
Revises: 
Create Date: 2023-06-24 23:52:28.246855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31a999f49cdc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quadratic_equations',
    sa.Column('value_a', sa.Integer(), nullable=False),
    sa.Column('value_b', sa.Integer(), nullable=False),
    sa.Column('value_c', sa.Integer(), nullable=False),
    sa.Column('value_x1', sa.Float(), nullable=True),
    sa.Column('value_x2', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quadratic_equations_created_at'), 'quadratic_equations', ['created_at'], unique=False)
    op.create_index(op.f('ix_quadratic_equations_updated_at'), 'quadratic_equations', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quadratic_equations_updated_at'), table_name='quadratic_equations')
    op.drop_index(op.f('ix_quadratic_equations_created_at'), table_name='quadratic_equations')
    op.drop_table('quadratic_equations')
    # ### end Alembic commands ###
